apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  nodeSelector:
    hardware-type: CPUONLY
   #For a server with GPUs
   #hardware-type: NVIDIAGPU 
  containers:
  - name:  test
    image: sachinbjohn/vwap:latest
    workingDir: /data
    command:
      - sleep
      - infinity
    volumeMounts:
      - mountPath: /data
        name: site-data
  volumes:
  - name: site-data
    persistentVolumeClaim:
      claimName: data-scratch